from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 1032)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")

        # Home Screen
        self.homeWindow = QtWidgets.QWidget()
        self.homeWindow.setObjectName("homeWindow")
        self.btnStart = QtWidgets.QPushButton(self.homeWindow)
        self.btnStart.setGeometry(QtCore.QRect(30, 50, 200, 100))
        self.btnStart.setObjectName("btnStart")
        self.btnSettings = QtWidgets.QPushButton(self.homeWindow)
        self.btnSettings.setGeometry(QtCore.QRect(30, 180, 200, 100))
        self.btnSettings.setObjectName("btnSettings")
        self.stackedWidget.addWidget(self.homeWindow)

        # Window1: Camera Stream and Navigation
        self.window1 = QtWidgets.QWidget()
        self.window1.setObjectName("window1")
        self.camera1Frame = QtWidgets.QLabel(self.window1)
        self.camera1Frame.setGeometry(QtCore.QRect(30, 20, 880, 640))
        self.camera1Frame.setMinimumSize(QtCore.QSize(640, 480))
        self.camera1Frame.setAlignment(QtCore.Qt.AlignCenter)
        self.camera1Frame.setObjectName("camera1Frame")
        self.btnNext1 = QtWidgets.QPushButton(self.window1)
        self.btnNext1.setGeometry(QtCore.QRect(940, 570, 200, 100))
        self.btnNext1.setObjectName("btnNext1")
        self.btnHome1 = QtWidgets.QPushButton(self.window1)
        self.btnHome1.setGeometry(QtCore.QRect(950, 40, 200, 100))
        self.btnHome1.setObjectName("btnHome1")
        self.stackedWidget.addWidget(self.window1)

        # Window2: List Display and Camera
        self.window2 = QtWidgets.QWidget()
        self.window2.setObjectName("window2")
        self.camera2Frame = QtWidgets.QLabel(self.window2)
        self.camera2Frame.setGeometry(QtCore.QRect(20, 40, 880, 640))
        self.camera2Frame.setMinimumSize(QtCore.QSize(640, 480))
        self.camera2Frame.setAlignment(QtCore.Qt.AlignCenter)
        self.camera2Frame.setObjectName("camera2Frame")
        self.listWidget = QtWidgets.QListWidget(self.window2)
        self.listWidget.setGeometry(QtCore.QRect(920, 40, 250, 521))
        self.listWidget.setObjectName("listWidget")
        self.btnComplete = QtWidgets.QPushButton(self.window2)
        self.btnComplete.setGeometry(QtCore.QRect(920, 580, 250, 100))
        self.btnComplete.setObjectName("btnComplete")
        self.stackedWidget.addWidget(self.window2)

        # Window3: Text Display and Charts
        self.window3 = QtWidgets.QWidget()
        self.window3.setObjectName("window3")
        self.textBox = QtWidgets.QTextEdit(self.window3)
        self.textBox.setGeometry(QtCore.QRect(50, 130, 1100, 300))
        self.textBox.setMinimumSize(QtCore.QSize(600, 300))
        self.textBox.setObjectName("textBox")
        self.btnHome3 = QtWidgets.QPushButton(self.window3)
        self.btnHome3.setGeometry(QtCore.QRect(960, 20, 200, 100))
        self.btnHome3.setObjectName("btnHome3")
        self.userName = QtWidgets.QLabel(self.window3)
        self.userName.setGeometry(QtCore.QRect(50, 20, 200, 100))
        self.userName.setObjectName("userName")
        self.chart3 = QtWidgets.QLabel(self.window3)
        self.chart3.setGeometry(QtCore.QRect(790, 460, 350, 250))
        self.chart3.setAlignment(QtCore.Qt.AlignCenter)
        self.chart3.setObjectName("chart3")
        self.chart2 = QtWidgets.QLabel(self.window3)
        self.chart2.setGeometry(QtCore.QRect(420, 460, 350, 250))
        self.chart2.setAlignment(QtCore.Qt.AlignCenter)
        self.chart2.setObjectName("chart2")
        self.chart1 = QtWidgets.QLabel(self.window3)
        self.chart1.setGeometry(QtCore.QRect(50, 460, 350, 250))
        self.chart1.setAlignment(QtCore.Qt.AlignCenter)
        self.chart1.setObjectName("chart1")
        self.stackedWidget.addWidget(self.window3)

        # Window 4: User Information Input
        self.window4 = QtWidgets.QWidget()
        self.window4.setObjectName("window4")
        self.labelName = QtWidgets.QLabel(self.window4)
        self.labelName.setGeometry(QtCore.QRect(10, 10, 60, 30))
        self.labelName.setText("Name:")
        self.editName = QtWidgets.QLineEdit(self.window4)
        self.editName.setGeometry(QtCore.QRect(80, 10, 200, 30))
        self.labelBirth = QtWidgets.QLabel(self.window4)
        self.labelBirth.setGeometry(QtCore.QRect(10, 50, 60, 30))
        self.labelBirth.setText("Birth Date:")
        self.editBirth = QtWidgets.QLineEdit(self.window4)
        self.editBirth.setGeometry(QtCore.QRect(80, 50, 200, 30))
        self.labelGender = QtWidgets.QLabel(self.window4)
        self.labelGender.setGeometry(QtCore.QRect(10, 90, 60, 30))
        self.labelGender.setText("Gender:")
        self.comboGender = QtWidgets.QComboBox(self.window4)
        self.comboGender.setGeometry(QtCore.QRect(80, 90, 200, 30))
        self.comboGender.addItems(["Male", "Female"])
        self.labelPhone = QtWidgets.QLabel(self.window4)
        self.labelPhone.setGeometry(QtCore.QRect(10, 130, 60, 30))
        self.labelPhone.setText("Phone:")
        self.editPhone = QtWidgets.QLineEdit(self.window4)
        self.editPhone.setGeometry(QtCore.QRect(80, 130, 200, 30))
        self.labelAddress = QtWidgets.QLabel(self.window4)
        self.labelAddress.setGeometry(QtCore.QRect(10, 170, 60, 30))
        self.labelAddress.setText("Address:")
        self.editAddress = QtWidgets.QLineEdit(self.window4)
        self.editAddress.setGeometry(QtCore.QRect(80, 170, 200, 30))
        self.labelHeight = QtWidgets.QLabel(self.window4)
        self.labelHeight.setGeometry(QtCore.QRect(10, 210, 60, 30))
        self.labelHeight.setText("Height:")
        self.editHeight = QtWidgets.QLineEdit(self.window4)
        self.editHeight.setGeometry(QtCore.QRect(80, 210, 200, 30))
        self.labelWeight = QtWidgets.QLabel(self.window4)
        self.labelWeight.setGeometry(QtCore.QRect(10, 250, 60, 30))
        self.labelWeight.setText("Weight:")
        self.editWeight = QtWidgets.QLineEdit(self.window4)
        self.editWeight.setGeometry(QtCore.QRect(80, 250, 200, 30))
        self.btnNext4 = QtWidgets.QPushButton(self.window4)
        self.btnNext4.setGeometry(QtCore.QRect(950, 590, 200, 100))
        self.btnNext4.setText("Next")
        self.btnHome4 = QtWidgets.QPushButton(self.window4)
        self.btnHome4.setGeometry(QtCore.QRect(950, 30, 200, 100))
        self.btnHome4.setText("Home")
        self.stackedWidget.addWidget(self.window4)

        # Window 5: Training Screen
        self.window5 = QtWidgets.QWidget()
        self.window5.setObjectName("window5")
        self.cameraTrainingFrame = QtWidgets.QLabel(self.window5)
        self.cameraTrainingFrame.setGeometry(QtCore.QRect(30, 40, 880, 640))
        self.cameraTrainingFrame.setAlignment(QtCore.Qt.AlignCenter)
        self.btnHome5 = QtWidgets.QPushButton(self.window5)
        self.btnHome5.setGeometry(QtCore.QRect(950, 30, 200, 100))
        self.btnHome5.setText("Home")
        self.btnNext5 = QtWidgets.QPushButton(self.window5)
        self.btnNext5.setGeometry(QtCore.QRect(950, 590, 200, 100))
        self.btnNext5.setText("Next")
        self.stackedWidget.addWidget(self.window5)

        # Final Setup
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Face Recognition"))
        self.btnStart.setText(_translate("MainWindow", "Start Recognition"))
        self.btnSettings.setText(_translate("MainWindow", "Register User"))
